name: ci
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
jobs:
  test:
    name: code quality and correctness
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Go 1.18
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - name: Checkout pull request head
        if: ${{ github.event_name == 'pull_request' }}
        run: git checkout HEAD^2

      # Configure runner environment
      - name: Set up runner environment
        run: ./.github/workflows/assets/utils.sh setup
        env:
          GITHUB_USER: ${{ github.actor }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # If "vendor" is in cache, restore.
      # To run conditional steps use:
      # if: steps.vendor-cache.outputs.cache-hit != 'true'
      - name: Restore modules from cache
        id: vendor-cache
        uses: actions/cache@v3.0.2
        env:
          cache-name: vendor
        with:
          path: ./vendor
          key: ${{ env.cache-name }}-${{ hashFiles('go.sum') }}

      # Run unit tests
      - name: Test
        run: |
          make test
          make benchmark

      # Populate vendor cache to speed up future runs
      - name: Populate vendor cache
        run: go mod vendor
