name: ci
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  test:
    name: code quality and correctness
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Go 1.18
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.18

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - name: Checkout pull request head
        if: ${{ github.event_name == 'pull_request' }}
        run: git checkout HEAD^2

      # Configure runner environment
      - name: Set up runner environment
        run: ./.github/workflows/assets/utils.sh setup
        env:
          GITHUB_USER: ${{ github.actor }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      # Run unit tests
      - name: Test
        run: |
          make test
          make benchmark
